### ISSUE TITLE
在授权Microsoft账户权限后出现错误：Call to undefined function curl_init()

### ISSUE THREAD

**Issue by caelricluo** [Tai7sy/OneDriveFly#44]
在授权Microsoft账户权限后出现错误：
>  Call to undefined function curl_init()
#0 OneDriveFly\index.php(36): curl('https://graph.m...', 0, NULL, Array)
#1 OneDriveFly\index.php(36): Library\OneDrive->info('/password')
#2 OneDriveFly\index.php(869): Library\OneDrive->get('/password')
#3 OneDriveFly\index.php(270): render(Array, Array, Array)
#4 OneDriveFly\index.php(62): handler(Object(Symfony\Component\HttpFoundation\Request))
#5 OneDriveFly\index.php(103): cgi_entry()
#6 {main}

url：
 >  /?oauth_callback=%7B"name"%3A"1"%2C"code"%3A"0.AXEAg-fyIXQ_L0mpLlLmvvIhsfcEgClRx1ZNq6OwWMAVT9JxAJQ.AQABAAIAAAD--DLA3VO7QrddgJg7WevrQFedDHx8-gxG9XvUMYLEbFzpJQfEgAjSXXpa-Y2IJCgui1teyrXbhAhNNGHjW_GdiUfCwBoQKTW1GnjGDG3WWBzLzu-Tx28GvX-crm1C7_fVwYwxIED5L2hBhmO4Kw0T8Z_ddkqd_9uOGBtCfo4ST91_s_DkvzxQKkyNYxfLWy733YLndJdpCU3T4huT8cTY4AwkhN5hQkAX5ANYVBmuQT6zb7qM9M0qoqcxENE5PSqEOjJzMwUW41jnDl2qaLlD_duFXZf_SWA79NvN7buR4GoGJs5Z7KBuqs6hmsJYg8egtgKJtugpSxiVWEba5oUWE7CBUbKvQqKT94b9nq0zu0djUxsRkl5Sz46EfWsJU55KAR_f7C895SunD7vxMN8rrX0jAli2or1_kOHriJ8H86IIVxFgUPmagSI210F_GhZpgi7Oay3GGpLmn6-6SXGVi9vcxhBLVO09RewlKTEtS6fbodw6oYu51fj7_RTsr3Yo15MYb4AN7PuoCJ1CeEKGuIl-FMTSh2Z1Mw8ordqp0Dif1cC-5k5RMcuRuElOcQhsYTf3r2l_Ta_Eq49Sh1EkfZQobtK1Dl67FIT0BIzdc5rqJ7AbPHLdFEfx1BYYfDWhxcyMsBZYM2-cyosmrvM-3FnBGINtioprwFj5wwVQLYNIlkYsU24AMqYEqd3yxLaH_gQA5M69MKa3eP7Fggr7Izozt-cXcWeKDLyiqTiFvsT0je410HsCSGOX87f55qEwvAgHC_3PU21MW5dKBPossG4jreH8PXgy5nmjn0ug3SAA"%2C"oauth"%3A%7B"redirect_uri"%3A"https%3A%2F%2Fonedrivefly.github.io"%2C"client_id"%3A"298004f7-c751-4d56-aba3-b058c0154fd2"%2C"client_secret"%3A"-%5E(!BpF-l9%2Fz%23%5B%2B*5t)alg%3B%5BV%40%3B%3B)_%5D%3B)%40j%23%5EE%3BT(%26%5E4uD%3B*%26%3F%232)>H%3F"%2C"oauth_url"%3A"https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2F"%2C"api_url"%3A"https%3A%2F%2Fgraph.microsoft.com%2Fv1.0%2Fme%2Fdrive%2Froot"%2C"scope"%3A"https%3A%2F%2Fgraph.microsoft.com%2FFiles.ReadWrite.All%20offline_access"%7D%7D

**Comment by Tai7sy** [comment]
php没有安装 curl 模块导致的, 需要安装

**Comment by caelricluo** [comment]
> php没有安装 curl 模块导致的, 需要安装

感谢你的回复。我刚刚试了下，还是不行
